#!/usr/bin/env bash

check_staging() 
{
 
  EXPECTED=18
  FOUND=`{ presapps ; versions ; } | wc -l`
  
  date
  echo "Checked staging, found $FOUND and was expecting $EXPECTED"
  
  if [ $FOUND -ne $EXPECTED ]
    then
      blink1-tool --rgb 0xff,0,00 --blink 95 &
  fi  
}

while :
do
  check_staging
  sleep 90
done  
