#!/usr/bin/env bash

check_staging() 
{
 
  # if all is fine "versions" should return 12 lines"
  EXPECTED=18
  FOUND=`{ presapps ; versions ; } | wc -l`
  
  echo "Checked staging, found $FOUND and was expecting $EXPECTED"
  
  if [ $FOUND -ne $EXPECTED ]
    then
      blink1-tool --rgb 0xff,0,00 --blink 40 &
  fi  
}

while :
do
  check_staging
  sleep 60
done  
